// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raft.proto

package grpc;

public final class Raft {
  private Raft() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestVoteReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestVoteReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 term = 1;</code>
     */
    long getTerm();

    /**
     * <code>int32 candidate_id = 2;</code>
     */
    int getCandidateId();

    /**
     * <code>int64 last_log_index = 3;</code>
     */
    long getLastLogIndex();

    /**
     * <code>int64 last_log_term = 4;</code>
     */
    long getLastLogTerm();
  }
  /**
   * Protobuf type {@code RequestVoteReq}
   */
  public  static final class RequestVoteReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestVoteReq)
      RequestVoteReqOrBuilder {
    // Use RequestVoteReq.newBuilder() to construct.
    private RequestVoteReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestVoteReq() {
      term_ = 0L;
      candidateId_ = 0;
      lastLogIndex_ = 0L;
      lastLogTerm_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestVoteReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              term_ = input.readInt64();
              break;
            }
            case 16: {

              candidateId_ = input.readInt32();
              break;
            }
            case 24: {

              lastLogIndex_ = input.readInt64();
              break;
            }
            case 32: {

              lastLogTerm_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Raft.internal_static_RequestVoteReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Raft.internal_static_RequestVoteReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Raft.RequestVoteReq.class, grpc.Raft.RequestVoteReq.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>int64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int CANDIDATE_ID_FIELD_NUMBER = 2;
    private int candidateId_;
    /**
     * <code>int32 candidate_id = 2;</code>
     */
    public int getCandidateId() {
      return candidateId_;
    }

    public static final int LAST_LOG_INDEX_FIELD_NUMBER = 3;
    private long lastLogIndex_;
    /**
     * <code>int64 last_log_index = 3;</code>
     */
    public long getLastLogIndex() {
      return lastLogIndex_;
    }

    public static final int LAST_LOG_TERM_FIELD_NUMBER = 4;
    private long lastLogTerm_;
    /**
     * <code>int64 last_log_term = 4;</code>
     */
    public long getLastLogTerm() {
      return lastLogTerm_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeInt64(1, term_);
      }
      if (candidateId_ != 0) {
        output.writeInt32(2, candidateId_);
      }
      if (lastLogIndex_ != 0L) {
        output.writeInt64(3, lastLogIndex_);
      }
      if (lastLogTerm_ != 0L) {
        output.writeInt64(4, lastLogTerm_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, term_);
      }
      if (candidateId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, candidateId_);
      }
      if (lastLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, lastLogIndex_);
      }
      if (lastLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastLogTerm_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Raft.RequestVoteReq)) {
        return super.equals(obj);
      }
      grpc.Raft.RequestVoteReq other = (grpc.Raft.RequestVoteReq) obj;

      boolean result = true;
      result = result && (getTerm()
          == other.getTerm());
      result = result && (getCandidateId()
          == other.getCandidateId());
      result = result && (getLastLogIndex()
          == other.getLastLogIndex());
      result = result && (getLastLogTerm()
          == other.getLastLogTerm());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + CANDIDATE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCandidateId();
      hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogIndex());
      hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogTerm());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Raft.RequestVoteReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Raft.RequestVoteReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.RequestVoteReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Raft.RequestVoteReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestVoteReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestVoteReq)
        grpc.Raft.RequestVoteReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Raft.internal_static_RequestVoteReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Raft.internal_static_RequestVoteReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Raft.RequestVoteReq.class, grpc.Raft.RequestVoteReq.Builder.class);
      }

      // Construct using grpc.Raft.RequestVoteReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0L;

        candidateId_ = 0;

        lastLogIndex_ = 0L;

        lastLogTerm_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Raft.internal_static_RequestVoteReq_descriptor;
      }

      public grpc.Raft.RequestVoteReq getDefaultInstanceForType() {
        return grpc.Raft.RequestVoteReq.getDefaultInstance();
      }

      public grpc.Raft.RequestVoteReq build() {
        grpc.Raft.RequestVoteReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.Raft.RequestVoteReq buildPartial() {
        grpc.Raft.RequestVoteReq result = new grpc.Raft.RequestVoteReq(this);
        result.term_ = term_;
        result.candidateId_ = candidateId_;
        result.lastLogIndex_ = lastLogIndex_;
        result.lastLogTerm_ = lastLogTerm_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Raft.RequestVoteReq) {
          return mergeFrom((grpc.Raft.RequestVoteReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Raft.RequestVoteReq other) {
        if (other == grpc.Raft.RequestVoteReq.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getCandidateId() != 0) {
          setCandidateId(other.getCandidateId());
        }
        if (other.getLastLogIndex() != 0L) {
          setLastLogIndex(other.getLastLogIndex());
        }
        if (other.getLastLogTerm() != 0L) {
          setLastLogTerm(other.getLastLogTerm());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Raft.RequestVoteReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Raft.RequestVoteReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 1;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private int candidateId_ ;
      /**
       * <code>int32 candidate_id = 2;</code>
       */
      public int getCandidateId() {
        return candidateId_;
      }
      /**
       * <code>int32 candidate_id = 2;</code>
       */
      public Builder setCandidateId(int value) {
        
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 candidate_id = 2;</code>
       */
      public Builder clearCandidateId() {
        
        candidateId_ = 0;
        onChanged();
        return this;
      }

      private long lastLogIndex_ ;
      /**
       * <code>int64 last_log_index = 3;</code>
       */
      public long getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>int64 last_log_index = 3;</code>
       */
      public Builder setLastLogIndex(long value) {
        
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_log_index = 3;</code>
       */
      public Builder clearLastLogIndex() {
        
        lastLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogTerm_ ;
      /**
       * <code>int64 last_log_term = 4;</code>
       */
      public long getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <code>int64 last_log_term = 4;</code>
       */
      public Builder setLastLogTerm(long value) {
        
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_log_term = 4;</code>
       */
      public Builder clearLastLogTerm() {
        
        lastLogTerm_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestVoteReq)
    }

    // @@protoc_insertion_point(class_scope:RequestVoteReq)
    private static final grpc.Raft.RequestVoteReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Raft.RequestVoteReq();
    }

    public static grpc.Raft.RequestVoteReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestVoteReq>
        PARSER = new com.google.protobuf.AbstractParser<RequestVoteReq>() {
      public RequestVoteReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestVoteReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestVoteReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestVoteReq> getParserForType() {
      return PARSER;
    }

    public grpc.Raft.RequestVoteReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestVoteRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestVoteResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 term = 1;</code>
     */
    long getTerm();

    /**
     * <code>bool vote_granted = 2;</code>
     */
    boolean getVoteGranted();
  }
  /**
   * Protobuf type {@code RequestVoteResp}
   */
  public  static final class RequestVoteResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestVoteResp)
      RequestVoteRespOrBuilder {
    // Use RequestVoteResp.newBuilder() to construct.
    private RequestVoteResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestVoteResp() {
      term_ = 0L;
      voteGranted_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestVoteResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              term_ = input.readInt64();
              break;
            }
            case 16: {

              voteGranted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Raft.internal_static_RequestVoteResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Raft.internal_static_RequestVoteResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Raft.RequestVoteResp.class, grpc.Raft.RequestVoteResp.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>int64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int VOTE_GRANTED_FIELD_NUMBER = 2;
    private boolean voteGranted_;
    /**
     * <code>bool vote_granted = 2;</code>
     */
    public boolean getVoteGranted() {
      return voteGranted_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeInt64(1, term_);
      }
      if (voteGranted_ != false) {
        output.writeBool(2, voteGranted_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, term_);
      }
      if (voteGranted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, voteGranted_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Raft.RequestVoteResp)) {
        return super.equals(obj);
      }
      grpc.Raft.RequestVoteResp other = (grpc.Raft.RequestVoteResp) obj;

      boolean result = true;
      result = result && (getTerm()
          == other.getTerm());
      result = result && (getVoteGranted()
          == other.getVoteGranted());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + VOTE_GRANTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVoteGranted());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Raft.RequestVoteResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Raft.RequestVoteResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.RequestVoteResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Raft.RequestVoteResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestVoteResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestVoteResp)
        grpc.Raft.RequestVoteRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Raft.internal_static_RequestVoteResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Raft.internal_static_RequestVoteResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Raft.RequestVoteResp.class, grpc.Raft.RequestVoteResp.Builder.class);
      }

      // Construct using grpc.Raft.RequestVoteResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0L;

        voteGranted_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Raft.internal_static_RequestVoteResp_descriptor;
      }

      public grpc.Raft.RequestVoteResp getDefaultInstanceForType() {
        return grpc.Raft.RequestVoteResp.getDefaultInstance();
      }

      public grpc.Raft.RequestVoteResp build() {
        grpc.Raft.RequestVoteResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.Raft.RequestVoteResp buildPartial() {
        grpc.Raft.RequestVoteResp result = new grpc.Raft.RequestVoteResp(this);
        result.term_ = term_;
        result.voteGranted_ = voteGranted_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Raft.RequestVoteResp) {
          return mergeFrom((grpc.Raft.RequestVoteResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Raft.RequestVoteResp other) {
        if (other == grpc.Raft.RequestVoteResp.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getVoteGranted() != false) {
          setVoteGranted(other.getVoteGranted());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Raft.RequestVoteResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Raft.RequestVoteResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 1;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean voteGranted_ ;
      /**
       * <code>bool vote_granted = 2;</code>
       */
      public boolean getVoteGranted() {
        return voteGranted_;
      }
      /**
       * <code>bool vote_granted = 2;</code>
       */
      public Builder setVoteGranted(boolean value) {
        
        voteGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool vote_granted = 2;</code>
       */
      public Builder clearVoteGranted() {
        
        voteGranted_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RequestVoteResp)
    }

    // @@protoc_insertion_point(class_scope:RequestVoteResp)
    private static final grpc.Raft.RequestVoteResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Raft.RequestVoteResp();
    }

    public static grpc.Raft.RequestVoteResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestVoteResp>
        PARSER = new com.google.protobuf.AbstractParser<RequestVoteResp>() {
      public RequestVoteResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestVoteResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestVoteResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestVoteResp> getParserForType() {
      return PARSER;
    }

    public grpc.Raft.RequestVoteResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntriesReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 term = 1;</code>
     */
    long getTerm();

    /**
     * <code>int32 leader_id = 2;</code>
     */
    int getLeaderId();

    /**
     * <code>int64 pre_log_index = 3;</code>
     */
    long getPreLogIndex();

    /**
     * <code>int64 pre_log_term = 4;</code>
     */
    long getPreLogTerm();

    /**
     * <code>repeated int64 entries = 5;</code>
     */
    java.util.List<java.lang.Long> getEntriesList();
    /**
     * <code>repeated int64 entries = 5;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated int64 entries = 5;</code>
     */
    long getEntries(int index);

    /**
     * <code>int64 leader_commit = 6;</code>
     */
    long getLeaderCommit();
  }
  /**
   * Protobuf type {@code AppendEntriesReq}
   */
  public  static final class AppendEntriesReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppendEntriesReq)
      AppendEntriesReqOrBuilder {
    // Use AppendEntriesReq.newBuilder() to construct.
    private AppendEntriesReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesReq() {
      term_ = 0L;
      leaderId_ = 0;
      preLogIndex_ = 0L;
      preLogTerm_ = 0L;
      entries_ = java.util.Collections.emptyList();
      leaderCommit_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppendEntriesReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              term_ = input.readInt64();
              break;
            }
            case 16: {

              leaderId_ = input.readInt32();
              break;
            }
            case 24: {

              preLogIndex_ = input.readInt64();
              break;
            }
            case 32: {

              preLogTerm_ = input.readInt64();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                entries_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              entries_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                entries_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                entries_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 48: {

              leaderCommit_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Raft.internal_static_AppendEntriesReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Raft.internal_static_AppendEntriesReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Raft.AppendEntriesReq.class, grpc.Raft.AppendEntriesReq.Builder.class);
    }

    private int bitField0_;
    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>int64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int LEADER_ID_FIELD_NUMBER = 2;
    private int leaderId_;
    /**
     * <code>int32 leader_id = 2;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int PRE_LOG_INDEX_FIELD_NUMBER = 3;
    private long preLogIndex_;
    /**
     * <code>int64 pre_log_index = 3;</code>
     */
    public long getPreLogIndex() {
      return preLogIndex_;
    }

    public static final int PRE_LOG_TERM_FIELD_NUMBER = 4;
    private long preLogTerm_;
    /**
     * <code>int64 pre_log_term = 4;</code>
     */
    public long getPreLogTerm() {
      return preLogTerm_;
    }

    public static final int ENTRIES_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> entries_;
    /**
     * <code>repeated int64 entries = 5;</code>
     */
    public java.util.List<java.lang.Long>
        getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated int64 entries = 5;</code>
     */
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated int64 entries = 5;</code>
     */
    public long getEntries(int index) {
      return entries_.get(index);
    }
    private int entriesMemoizedSerializedSize = -1;

    public static final int LEADER_COMMIT_FIELD_NUMBER = 6;
    private long leaderCommit_;
    /**
     * <code>int64 leader_commit = 6;</code>
     */
    public long getLeaderCommit() {
      return leaderCommit_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (term_ != 0L) {
        output.writeInt64(1, term_);
      }
      if (leaderId_ != 0) {
        output.writeInt32(2, leaderId_);
      }
      if (preLogIndex_ != 0L) {
        output.writeInt64(3, preLogIndex_);
      }
      if (preLogTerm_ != 0L) {
        output.writeInt64(4, preLogTerm_);
      }
      if (getEntriesList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(entriesMemoizedSerializedSize);
      }
      for (int i = 0; i < entries_.size(); i++) {
        output.writeInt64NoTag(entries_.get(i));
      }
      if (leaderCommit_ != 0L) {
        output.writeInt64(6, leaderCommit_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, term_);
      }
      if (leaderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leaderId_);
      }
      if (preLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, preLogIndex_);
      }
      if (preLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, preLogTerm_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < entries_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(entries_.get(i));
        }
        size += dataSize;
        if (!getEntriesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        entriesMemoizedSerializedSize = dataSize;
      }
      if (leaderCommit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, leaderCommit_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Raft.AppendEntriesReq)) {
        return super.equals(obj);
      }
      grpc.Raft.AppendEntriesReq other = (grpc.Raft.AppendEntriesReq) obj;

      boolean result = true;
      result = result && (getTerm()
          == other.getTerm());
      result = result && (getLeaderId()
          == other.getLeaderId());
      result = result && (getPreLogIndex()
          == other.getPreLogIndex());
      result = result && (getPreLogTerm()
          == other.getPreLogTerm());
      result = result && getEntriesList()
          .equals(other.getEntriesList());
      result = result && (getLeaderCommit()
          == other.getLeaderCommit());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLeaderId();
      hash = (37 * hash) + PRE_LOG_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPreLogIndex());
      hash = (37 * hash) + PRE_LOG_TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPreLogTerm());
      if (getEntriesCount() > 0) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntriesList().hashCode();
      }
      hash = (37 * hash) + LEADER_COMMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLeaderCommit());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Raft.AppendEntriesReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Raft.AppendEntriesReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.AppendEntriesReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Raft.AppendEntriesReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntriesReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntriesReq)
        grpc.Raft.AppendEntriesReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Raft.internal_static_AppendEntriesReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Raft.internal_static_AppendEntriesReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Raft.AppendEntriesReq.class, grpc.Raft.AppendEntriesReq.Builder.class);
      }

      // Construct using grpc.Raft.AppendEntriesReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0L;

        leaderId_ = 0;

        preLogIndex_ = 0L;

        preLogTerm_ = 0L;

        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        leaderCommit_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Raft.internal_static_AppendEntriesReq_descriptor;
      }

      public grpc.Raft.AppendEntriesReq getDefaultInstanceForType() {
        return grpc.Raft.AppendEntriesReq.getDefaultInstance();
      }

      public grpc.Raft.AppendEntriesReq build() {
        grpc.Raft.AppendEntriesReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.Raft.AppendEntriesReq buildPartial() {
        grpc.Raft.AppendEntriesReq result = new grpc.Raft.AppendEntriesReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.term_ = term_;
        result.leaderId_ = leaderId_;
        result.preLogIndex_ = preLogIndex_;
        result.preLogTerm_ = preLogTerm_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.entries_ = entries_;
        result.leaderCommit_ = leaderCommit_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Raft.AppendEntriesReq) {
          return mergeFrom((grpc.Raft.AppendEntriesReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Raft.AppendEntriesReq other) {
        if (other == grpc.Raft.AppendEntriesReq.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getLeaderId() != 0) {
          setLeaderId(other.getLeaderId());
        }
        if (other.getPreLogIndex() != 0L) {
          setPreLogIndex(other.getPreLogIndex());
        }
        if (other.getPreLogTerm() != 0L) {
          setPreLogTerm(other.getPreLogTerm());
        }
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
        if (other.getLeaderCommit() != 0L) {
          setLeaderCommit(other.getLeaderCommit());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Raft.AppendEntriesReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Raft.AppendEntriesReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long term_ ;
      /**
       * <code>int64 term = 1;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>int32 leader_id = 2;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>int32 leader_id = 2;</code>
       */
      public Builder setLeaderId(int value) {
        
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 leader_id = 2;</code>
       */
      public Builder clearLeaderId() {
        
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private long preLogIndex_ ;
      /**
       * <code>int64 pre_log_index = 3;</code>
       */
      public long getPreLogIndex() {
        return preLogIndex_;
      }
      /**
       * <code>int64 pre_log_index = 3;</code>
       */
      public Builder setPreLogIndex(long value) {
        
        preLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 pre_log_index = 3;</code>
       */
      public Builder clearPreLogIndex() {
        
        preLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long preLogTerm_ ;
      /**
       * <code>int64 pre_log_term = 4;</code>
       */
      public long getPreLogTerm() {
        return preLogTerm_;
      }
      /**
       * <code>int64 pre_log_term = 4;</code>
       */
      public Builder setPreLogTerm(long value) {
        
        preLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 pre_log_term = 4;</code>
       */
      public Builder clearPreLogTerm() {
        
        preLogTerm_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> entries_ = java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          entries_ = new java.util.ArrayList<java.lang.Long>(entries_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public java.util.List<java.lang.Long>
          getEntriesList() {
        return java.util.Collections.unmodifiableList(entries_);
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public int getEntriesCount() {
        return entries_.size();
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public long getEntries(int index) {
        return entries_.get(index);
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public Builder setEntries(
          int index, long value) {
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public Builder addEntries(long value) {
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 entries = 5;</code>
       */
      public Builder clearEntries() {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private long leaderCommit_ ;
      /**
       * <code>int64 leader_commit = 6;</code>
       */
      public long getLeaderCommit() {
        return leaderCommit_;
      }
      /**
       * <code>int64 leader_commit = 6;</code>
       */
      public Builder setLeaderCommit(long value) {
        
        leaderCommit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 leader_commit = 6;</code>
       */
      public Builder clearLeaderCommit() {
        
        leaderCommit_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AppendEntriesReq)
    }

    // @@protoc_insertion_point(class_scope:AppendEntriesReq)
    private static final grpc.Raft.AppendEntriesReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Raft.AppendEntriesReq();
    }

    public static grpc.Raft.AppendEntriesReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesReq>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesReq>() {
      public AppendEntriesReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppendEntriesReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesReq> getParserForType() {
      return PARSER;
    }

    public grpc.Raft.AppendEntriesReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AppendEntriesResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 term = 1;</code>
     */
    long getTerm();

    /**
     * <code>bool success = 2;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code AppendEntriesResp}
   */
  public  static final class AppendEntriesResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AppendEntriesResp)
      AppendEntriesRespOrBuilder {
    // Use AppendEntriesResp.newBuilder() to construct.
    private AppendEntriesResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesResp() {
      term_ = 0L;
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppendEntriesResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              term_ = input.readInt64();
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.Raft.internal_static_AppendEntriesResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.Raft.internal_static_AppendEntriesResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.Raft.AppendEntriesResp.class, grpc.Raft.AppendEntriesResp.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>int64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeInt64(1, term_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, term_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc.Raft.AppendEntriesResp)) {
        return super.equals(obj);
      }
      grpc.Raft.AppendEntriesResp other = (grpc.Raft.AppendEntriesResp) obj;

      boolean result = true;
      result = result && (getTerm()
          == other.getTerm());
      result = result && (getSuccess()
          == other.getSuccess());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc.Raft.AppendEntriesResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc.Raft.AppendEntriesResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc.Raft.AppendEntriesResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.Raft.AppendEntriesResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AppendEntriesResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AppendEntriesResp)
        grpc.Raft.AppendEntriesRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.Raft.internal_static_AppendEntriesResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.Raft.internal_static_AppendEntriesResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.Raft.AppendEntriesResp.class, grpc.Raft.AppendEntriesResp.Builder.class);
      }

      // Construct using grpc.Raft.AppendEntriesResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0L;

        success_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.Raft.internal_static_AppendEntriesResp_descriptor;
      }

      public grpc.Raft.AppendEntriesResp getDefaultInstanceForType() {
        return grpc.Raft.AppendEntriesResp.getDefaultInstance();
      }

      public grpc.Raft.AppendEntriesResp build() {
        grpc.Raft.AppendEntriesResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.Raft.AppendEntriesResp buildPartial() {
        grpc.Raft.AppendEntriesResp result = new grpc.Raft.AppendEntriesResp(this);
        result.term_ = term_;
        result.success_ = success_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.Raft.AppendEntriesResp) {
          return mergeFrom((grpc.Raft.AppendEntriesResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.Raft.AppendEntriesResp other) {
        if (other == grpc.Raft.AppendEntriesResp.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.Raft.AppendEntriesResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.Raft.AppendEntriesResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>int64 term = 1;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AppendEntriesResp)
    }

    // @@protoc_insertion_point(class_scope:AppendEntriesResp)
    private static final grpc.Raft.AppendEntriesResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.Raft.AppendEntriesResp();
    }

    public static grpc.Raft.AppendEntriesResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesResp>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesResp>() {
      public AppendEntriesResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AppendEntriesResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppendEntriesResp> getParserForType() {
      return PARSER;
    }

    public grpc.Raft.AppendEntriesResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVoteReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestVoteReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVoteResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestVoteResp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntriesReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AppendEntriesResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AppendEntriesResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nraft.proto\"c\n\016RequestVoteReq\022\014\n\004term\030\001" +
      " \001(\003\022\024\n\014candidate_id\030\002 \001(\005\022\026\n\016last_log_i" +
      "ndex\030\003 \001(\003\022\025\n\rlast_log_term\030\004 \001(\003\"5\n\017Req" +
      "uestVoteResp\022\014\n\004term\030\001 \001(\003\022\024\n\014vote_grant" +
      "ed\030\002 \001(\010\"\210\001\n\020AppendEntriesReq\022\014\n\004term\030\001 " +
      "\001(\003\022\021\n\tleader_id\030\002 \001(\005\022\025\n\rpre_log_index\030" +
      "\003 \001(\003\022\024\n\014pre_log_term\030\004 \001(\003\022\017\n\007entries\030\005" +
      " \003(\003\022\025\n\rleader_commit\030\006 \001(\003\"2\n\021AppendEnt" +
      "riesResp\022\014\n\004term\030\001 \001(\003\022\017\n\007success\030\002 \001(\0102" +
      "{\n\017RaftCommService\0220\n\013RequestVote\022\017.Requ",
      "estVoteReq\032\020.RequestVoteResp\0226\n\rAppendEn" +
      "tries\022\021.AppendEntriesReq\032\022.AppendEntries" +
      "RespB\006\n\004grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestVoteReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestVoteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestVoteReq_descriptor,
        new java.lang.String[] { "Term", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_RequestVoteResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RequestVoteResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestVoteResp_descriptor,
        new java.lang.String[] { "Term", "VoteGranted", });
    internal_static_AppendEntriesReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AppendEntriesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntriesReq_descriptor,
        new java.lang.String[] { "Term", "LeaderId", "PreLogIndex", "PreLogTerm", "Entries", "LeaderCommit", });
    internal_static_AppendEntriesResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AppendEntriesResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AppendEntriesResp_descriptor,
        new java.lang.String[] { "Term", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
